"use client";

import { motion } from 'framer-motion';
import Image from 'next/image';
import Link from 'next/link';
import { FaExternalLinkAlt, FaArrowLeft, FaShieldAlt, FaRobot, FaFileAlt, FaClock } from 'react-icons/fa';
import Footer from '@/components/Footer';

export default function LeastByJustePage() {
  const technologies = [
    "Python 3.13", "FastAPI", "Next.js 14", "Tailwind CSS",
    "Supabase", "PostgreSQL", "Google Admin SDK", "Claude AI (claude-sonnet-4-6)",
    "Resend", "Stripe", "Vercel", "Render", "PKCE OAuth 2.0", "ReportLab"
  ];

  const features = [
    {
      icon: "shield",
      title: "9-Rule Deterministic Risk Engine",
      description: "Pure Python functions, no ML. 4 HIGH severity rules (RULE-001 through -003, -008) and 5 MEDIUM rules covering super admins, service accounts, group bloat, MFA gaps, dormant accounts, and more. Maps directly to SOC 2 CC6.x controls."
    },
    {
      icon: "robot",
      title: "AI-Powered Explanations",
      description: "Each risk finding is enriched with a plain-English explanation and remediation recommendation generated by Claude (claude-sonnet-4-6). Includes graceful fallback if the AI layer is unavailable — the deterministic engine always runs first."
    },
    {
      icon: "clock",
      title: "Automated Daily Scans",
      description: "Vercel Cron triggers a scan at 08:00 UTC every day. The cron endpoint calls the Render backend, which queries the Google Admin SDK, runs the risk engine, enriches findings, and stores results in Supabase. Email summary sent via Resend."
    },
    {
      icon: "file",
      title: "PDF Audit Reports",
      description: "On-demand PDF generation using ReportLab. Reports include finding counts, risk breakdown, framework citations (SOC 2, ISO 27001), and per-finding details with AI recommendations. Generated in-memory, streamed to the browser."
    },
    {
      icon: "shield",
      title: "PKCE OAuth 2.0 + Google Admin SDK",
      description: "Three read-only Google Workspace scopes: Admin Directory users/groups/roles. PKCE flow with in-memory code_verifier cache keyed by user_id. Connected workspaces stored in tenant_connections table with one connection per user."
    },
    {
      icon: "shield",
      title: "SOC 2-Aligned Evidence",
      description: "Every finding cites specific SOC 2 Trust Services Criteria: CC6.1, CC6.3, CC6.6, CC6.7. Designed for SMBs preparing for their first SOC 2 audit who need automated access review evidence without a dedicated GRC team."
    }
  ];

  const architecture = [
    { layer: "Frontend", stack: "Next.js 14 · Tailwind CSS · shadcn/ui", host: "Vercel" },
    { layer: "Backend API", stack: "Python 3.13 · FastAPI · 10 routers", host: "Render" },
    { layer: "Database", stack: "Supabase PostgreSQL · 4 tables", host: "Supabase" },
    { layer: "Auth", stack: "Supabase Auth + PKCE OAuth 2.0 (Google)", host: "Google Cloud" },
    { layer: "AI Layer", stack: "Anthropic claude-sonnet-4-6", host: "Anthropic API" },
    { layer: "Email", stack: "Resend transactional email", host: "Resend" },
    { layer: "Cron", stack: "Vercel Cron → Render admin endpoint", host: "Vercel + Render" },
    { layer: "Billing", stack: "Stripe (configured)", host: "Stripe" },
  ];

  const riskRules = [
    { id: "RULE-001", severity: "HIGH",   title: "Super Admin detection",                    framework: "CC6.3" },
    { id: "RULE-002", severity: "HIGH",   title: "Service account with admin privileges",     framework: "CC6.6" },
    { id: "RULE-003", severity: "HIGH",   title: "Suspended user retains group memberships",  framework: "CC6.7" },
    { id: "RULE-008", severity: "HIGH",   title: "Shared account in production environment",  framework: "CC6.1" },
    { id: "RULE-004", severity: "MEDIUM", title: "User in excessive number of groups",        framework: "CC6.3" },
    { id: "RULE-005", severity: "MEDIUM", title: "User without MFA accessing sensitive data", framework: "CC6.6" },
    { id: "RULE-006", severity: "MEDIUM", title: "External user with internal access",        framework: "CC6.7" },
    { id: "RULE-007", severity: "MEDIUM", title: "Dormant service account (90+ days)",        framework: "CC6.1" },
    { id: "RULE-009", severity: "MEDIUM", title: "Role assigned outside standard group",      framework: "CC6.3" },
  ];

  return (
    <div className="min-h-screen bg-white dark:bg-gray-900 pt-20">
      {/* Hero */}
      <div className="bg-gradient-to-br from-[#0a0f1e] to-[#1a2b4c] text-white py-20">
        <div className="container mx-auto px-6">
          <Link href="/projects" className="inline-flex items-center text-[#c9a84c] hover:text-yellow-300 mb-8 transition-colors">
            <FaArrowLeft className="mr-2" /> Back to Projects
          </Link>

          <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.5 }}>
            <div className="inline-block px-3 py-1 rounded-full bg-[#c9a84c]/20 border border-[#c9a84c]/40 text-[#c9a84c] text-xs font-medium mb-4 uppercase tracking-widest">
              Live Product · Full-Stack · IAM SaaS
            </div>
            <h1 className="text-4xl md:text-5xl font-bold mb-4">Least by Juste™</h1>
            <p className="text-xl text-gray-300 mb-2">Least Privilege. Proven.</p>
            <p className="text-gray-400 max-w-2xl mb-8">
              Access review autopilot for Google Workspace. A production IAM SaaS that runs a 9-rule
              deterministic risk engine, enriches every finding with Claude AI, generates PDF audit
              reports, and runs automated daily scans — built solo from scratch in 2025–2026.
            </p>

            <div className="flex flex-wrap gap-4">
              <a
                href="https://app.getleast.io"
                target="_blank"
                rel="noreferrer"
                className="inline-flex items-center px-6 py-3 bg-[#c9a84c] hover:bg-yellow-400 text-[#0a0f1e] font-bold rounded-lg transition duration-300"
              >
                <FaExternalLinkAlt className="mr-2" /> Live App
              </a>
              <a
                href="https://usejuste.com"
                target="_blank"
                rel="noreferrer"
                className="inline-flex items-center px-6 py-3 bg-transparent border border-[#c9a84c]/50 text-[#c9a84c] hover:bg-[#c9a84c]/10 font-medium rounded-lg transition duration-300"
              >
                Product Site
              </a>
            </div>
          </motion.div>
        </div>
      </div>

      {/* Dashboard screenshot */}
      <div className="container mx-auto px-6 py-12">
        <motion.div
          initial={{ opacity: 0, y: 30 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.6, delay: 0.2 }}
          className="relative w-full rounded-xl overflow-hidden shadow-2xl border border-gray-200 dark:border-gray-700"
        >
          <Image
            src="/images/projects/least-by-juste/thumbnail.png"
            alt="Least by Juste™ Dashboard"
            width={1200}
            height={750}
            className="w-full h-auto"
            priority
          />
        </motion.div>
      </div>

      <div className="container mx-auto px-6 pb-16">

        {/* Architecture table */}
        <motion.section
          className="mb-16"
          initial={{ opacity: 0, y: 30 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          transition={{ duration: 0.5 }}
        >
          <h2 className="text-2xl font-bold text-gray-900 dark:text-white mb-6">Architecture</h2>
          <div className="overflow-x-auto rounded-lg border border-gray-200 dark:border-gray-700">
            <table className="w-full text-sm">
              <thead>
                <tr className="bg-gray-50 dark:bg-gray-800">
                  <th className="px-4 py-3 text-left text-gray-600 dark:text-gray-400 font-medium">Layer</th>
                  <th className="px-4 py-3 text-left text-gray-600 dark:text-gray-400 font-medium">Stack</th>
                  <th className="px-4 py-3 text-left text-gray-600 dark:text-gray-400 font-medium">Host</th>
                </tr>
              </thead>
              <tbody>
                {architecture.map((row, i) => (
                  <tr key={i} className={i % 2 === 0 ? "bg-white dark:bg-gray-900" : "bg-gray-50 dark:bg-gray-800/50"}>
                    <td className="px-4 py-3 font-medium text-blue-600 dark:text-blue-400">{row.layer}</td>
                    <td className="px-4 py-3 text-gray-700 dark:text-gray-300 font-mono text-xs">{row.stack}</td>
                    <td className="px-4 py-3 text-gray-500 dark:text-gray-400">{row.host}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </motion.section>

        {/* Risk Rules */}
        <motion.section
          className="mb-16"
          initial={{ opacity: 0, y: 30 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          transition={{ duration: 0.5 }}
        >
          <h2 className="text-2xl font-bold text-gray-900 dark:text-white mb-2">9-Rule Risk Engine</h2>
          <p className="text-gray-500 dark:text-gray-400 mb-6">
            Pure deterministic Python functions — no ML, no model drift, no hallucinated findings.
            Every rule maps to a specific SOC 2 Trust Services Criteria.
          </p>
          <div className="overflow-x-auto rounded-lg border border-gray-200 dark:border-gray-700">
            <table className="w-full text-sm">
              <thead>
                <tr className="bg-gray-50 dark:bg-gray-800">
                  <th className="px-4 py-3 text-left text-gray-600 dark:text-gray-400 font-medium">Rule ID</th>
                  <th className="px-4 py-3 text-left text-gray-600 dark:text-gray-400 font-medium">Severity</th>
                  <th className="px-4 py-3 text-left text-gray-600 dark:text-gray-400 font-medium">Finding</th>
                  <th className="px-4 py-3 text-left text-gray-600 dark:text-gray-400 font-medium">SOC 2</th>
                </tr>
              </thead>
              <tbody>
                {riskRules.map((rule, i) => (
                  <tr key={i} className={i % 2 === 0 ? "bg-white dark:bg-gray-900" : "bg-gray-50 dark:bg-gray-800/50"}>
                    <td className="px-4 py-3 font-mono text-blue-600 dark:text-blue-400 text-xs">{rule.id}</td>
                    <td className="px-4 py-3">
                      <span className={`inline-block px-2 py-0.5 rounded text-xs font-bold ${
                        rule.severity === 'HIGH'
                          ? 'bg-red-100 dark:bg-red-900/30 text-red-700 dark:text-red-400'
                          : 'bg-amber-100 dark:bg-amber-900/30 text-amber-700 dark:text-amber-400'
                      }`}>
                        {rule.severity}
                      </span>
                    </td>
                    <td className="px-4 py-3 text-gray-700 dark:text-gray-300">{rule.title}</td>
                    <td className="px-4 py-3 text-gray-500 dark:text-gray-400 font-mono text-xs">{rule.framework}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </motion.section>

        {/* Features grid */}
        <motion.section
          className="mb-16"
          initial={{ opacity: 0, y: 30 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          transition={{ duration: 0.5 }}
        >
          <h2 className="text-2xl font-bold text-gray-900 dark:text-white mb-6">Features</h2>
          <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-6">
            {features.map((feature, i) => (
              <motion.div
                key={i}
                className="p-6 bg-gray-50 dark:bg-gray-800 rounded-xl border border-gray-200 dark:border-gray-700"
                initial={{ opacity: 0, y: 20 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true }}
                transition={{ duration: 0.4, delay: i * 0.08 }}
              >
                <h3 className="text-base font-semibold text-gray-900 dark:text-white mb-2">{feature.title}</h3>
                <p className="text-sm text-gray-600 dark:text-gray-400 leading-relaxed">{feature.description}</p>
              </motion.div>
            ))}
          </div>
        </motion.section>

        {/* Tech stack */}
        <motion.section
          className="mb-16"
          initial={{ opacity: 0, y: 30 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          transition={{ duration: 0.5 }}
        >
          <h2 className="text-2xl font-bold text-gray-900 dark:text-white mb-4">Full Stack</h2>
          <div className="flex flex-wrap gap-2">
            {technologies.map((tech) => (
              <span
                key={tech}
                className="px-3 py-1 bg-blue-50 dark:bg-blue-900/20 text-blue-700 dark:text-blue-300 text-sm rounded-full border border-blue-200 dark:border-blue-800"
              >
                {tech}
              </span>
            ))}
          </div>
        </motion.section>

        {/* CTA */}
        <motion.div
          className="bg-gradient-to-br from-[#0a0f1e] to-[#1a2b4c] rounded-2xl p-8 text-center"
          initial={{ opacity: 0, y: 30 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          transition={{ duration: 0.5 }}
        >
          <h2 className="text-2xl font-bold text-white mb-2">Try it live</h2>
          <p className="text-gray-400 mb-6 max-w-md mx-auto">
            Connect your Google Workspace and run your first access review in under 10 minutes.
          </p>
          <a
            href="https://app.getleast.io"
            target="_blank"
            rel="noreferrer"
            className="inline-flex items-center px-8 py-3 bg-[#c9a84c] hover:bg-yellow-400 text-[#0a0f1e] font-bold rounded-lg transition duration-300"
          >
            <FaExternalLinkAlt className="mr-2" /> Open Least by Juste™
          </a>
        </motion.div>
      </div>

      <Footer />
    </div>
  );
}
